(define make-account (lambda (balance password)
	(define withdraw (lambda (amount)
		(if (>= balance amount)
			(begin (set! balance (- balance amount))
				balance)
			"Insufficient funds") ))
	(define deposit (lambda (amount)
		(set! balance (+ balance amount))
		balance))
	(define authError (lambda (amount)
		"Incorrect password"))
	(define dispatch (lambda(p m)
		(if (not (eq? p password))
			authError
			(cond ((eq? m 'withdraw) withdraw)
				((eq? m 'deposit) deposit)
				(else (error "Unknown request -- MAKE-ACCOUNT" m)) )) ))
	dispatch
))
