(define make-account (lambda (balance password)
	(define withdraw (lambda (amount)
		(if (>= balance amount)
			(begin (set! balance (- balance amount))
				balance)
			"Insufficient funds") ))
	(define deposit (lambda (amount)
		(set! balance (+ balance amount))
		balance))
	(define check-password (lambda (p)
		(eq? p password) ))
	(define authError (lambda (amount)
		"Incorrect password"))
	(define dispatch (lambda(p m)
		(cond ((eq? m 'check-password) (check-password p))
			((not (check-password p)) authError)
			((eq? m 'withdraw) withdraw)
			((eq? m 'deposit) deposit)
			(else (error "Unknown request -- MAKE-ACCOUNT" m)) ) ))
	dispatch
))

(define make-joint (lambda (account old-password new-password)
	(define authError (lambda (amount)
		"Incorrect password"))
	(if (account old-password 'check-password)
		(lambda (password m)
			(if (eq? password new-password)
				(account old-password m)
				authError) )
		authError) ))
